name: Deploy to ECR

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v1
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: saminamurad
        aws-secret-access-key: Emadullah1*12
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: react-app1
        IMAGE_TAG: react-app1
      run: |
        docker build -t $ECR_REGISTRY/$react-app:$react-app1 .
        docker push $ECR_REGISTRY/$react-app:$react-app1
